### ISSUE TITLE
"same chain of narrators" and empty hadiths

### ISSUE THREAD

**Issue by theflightguy2** [fawazahmed0/hadith-api#11]
Salam

When we access the Hadith ENDPOINT for Sahih Muslim, we get many hadiths which are simply statements like 

`A hadith like this has been narrated on the authority of Abu Huraira (Allah be pleased with him) through another chain of transmitters` and we also get empty hadiths etc. is there any list of the hadith numbers that contain such things which aren't actual hadiths, so that we may block them out when we access the API? Or any other workaround that you could suggest?

Regards

**Comment by fawazahmed0** [comment]
For simple statements I am not sure if there is any reliable way to block it
For empty text, You can check in python whether the text is empty

**Comment by theflightguy2** [comment]
Ah ok, is there any list of all the hadiths in a simple txt so we can
identify the numbers involved and blacklist them when we search the API

**Comment by fawazahmed0** [comment]
currently, there is no list yet

**Comment by theflightguy2** [comment]
Ok.
