### ISSUE TITLE
Developed www.islam.quest using data provided by you :)

### ISSUE THREAD

**Issue by sohaibilyas** [fawazahmed0/hadith-api#14]
Hi Fawaz, I developed this website [islam.quest](https://islam.quest) which is an extremely fast hadith and quran search engine built using the data provided by you, kindly take a look at it and leave your feedback here, I just wanted to say thank you so much for your hard-work, keep it up.

**Comment by fawazahmed0** [comment]
Thats extremely fast mashallah, May Allah bless you for your work.

**Comment by sohaibilyas** [comment]
@fawazahmed0 may Allah bless you and reward you for the hard-work you have done for Islam, I could develop that website only because of the data provided by you, keep up the good work.
