### ISSUE TITLE
Wrong in-book reference in Muwatta Malik

### ISSUE THREAD

**Issue by unkn4wn** [fawazahmed0/hadith-api#15]
Asselamu Aleykum,
The "in-book reference"  in Muwatta Malik is everywhere the "hadithnumber". Example:
`"hadiths": [
		{
			"hadithnumber": 1020,
			"arabicnumber": 1020,
			"text": "Yahya related to me ....",
			"grades": [
				{
					"name": "Salim al-Hilali",
					"grade": "Sahih"
				}
			],
			"reference": {
				"book": 22,
				"hadith": 1020
			}
		}
	]`
	
Instead of "Book 22, Hadith 1020" it should be "Book 22, Hadith 8"

**Comment by fawazahmed0** [comment]
This is fixed now
