### ISSUE TITLE
Grading issue in zubair ali zai

### ISSUE THREAD

**Issue by unkn4wn** [fawazahmed0/hadith-api#18]
Asselamu aleykum,
Sometimes the hadith grade text differs from the original text. But maybe this is intended?
Example:
https://zubairalizai.com/nasai/#1305 says "Hadith Hasan" while
https://cdn.jsdelivr.net/gh/fawazahmed0/hadith-api@1/editions/eng-nasai/1304.json says "Hadith Hasan or Sahih"
(There is a minor difference in numeration but its actually the same hadith)

Is there any reason for this? The statement is correct because the Hadith is actually hasan but people could misinterpret "Hasan or Sahih" as the words of Sheikh Zubair even if he only said "hasan".

**Comment by fawazahmed0** [comment]
Thanks I will look it later

**Comment by Shahzad6077** [comment]
Hey @fawazahmed0, I would be glad to contribute.

**Comment by fawazahmed0** [comment]
Thanks @Shahzad6077 ,  I will fix this issue later (I already have made scripts before, which will make this task a lot easier) .
Meanwhile, you could get try to get [bangla translations](https://github.com/fawazahmed0/hadith-api/issues/12) (with corresponding arabic hadith ), if possible.

**Comment by GibreelAbdullah** [comment]
https://github.com/fawazahmed0/hadith-api/blob/1/editions/ara-nasai/6.json

Zubair Ali Zai's grading is given 3 times.

**Comment by fawazahmed0** [comment]
Thank you all of you for this issue, should be fixed now.

**More details:**
I scrapped zubair ali zai grades from [zubairalizai.com](https://zubairalizai.com) in march 2022, and at that time the website had completely wrong grades, recently(like 6 months ago) they seems to have fixed the issue with their grades.

I have rescrapped the new grades and updated the data in this api to fix this issue.

**Note:** You can verify the new grades using darussalam books (darussalam also uses zubair ali zai grades):
https://kalamullah.com/sunan-an-nasai.html
https://kalamullah.com/jami-at-tirmidhi.html
https://kalamullah.com/sunan-abu-dawood.html
https://kalamullah.com/ibn-majah.html
