### ISSUE TITLE
How hadith reference work?

### ISSUE THREAD

**Issue by kaisersakhi** [fawazahmed0/hadith-api#27]
Assalaamualikum brother,
I need all the books in a database, i'm converting all this json into a RDBMS but i have a little confusion..

///////////////////
      "reference": {
        "book": 4,
        "hadith": 1
      }
////////////////
Can you explain this bit, how does this work, i mean what is this book number and hadith number does it refers to the book of the same number and like wise hadith if so then book number shouldn't exceed 6, or in this case 7, but it does.
Please correct me!
Thank you!

**Comment by fawazahmed0** [comment]
[Book 4](https://fawazahmed0.github.io/hadiths/data.html?edition=eng-abudawud&type=section&num=4#hadith:eng-abudawud:1198:~:text=Reference%3A%20Book%204%20Hadith%201) refers to [section 4](https://fawazahmed0.github.io/hadiths/data.html?edition=eng-abudawud&type=section&num=4#:~:text=Search-,Section%204,-%3A%20Prayer%20\(Kitab%20Al) and so on.

**Comment by unkn4wn** [comment]
> Assalaamualikum brother,
> 
> I need all the books in a database, i'm converting all this json into a RDBMS but i have a little confusion..
> 
> 
> 
> ///////////////////
> 
>       "reference": {
> 
>         "book": 4,
> 
>         "hadith": 1
> 
>       }
> 
> ////////////////
> 
> Can you explain this bit, how does this work, i mean what is this book number and hadith number does it refers to the book of the same number and like wise hadith if so then book number shouldn't exceed 6, or in this case 7, but it does.
> 
> Please correct me!
> 
> Thank you!

Wa aleykum assalam wa rahmatullahi wa barakatuh,
It would be great if you upload your RDBMS or the script after you've finished, so we can all benefit from that.

**Comment by kaisersakhi** [comment]
> [Book 4](https://fawazahmed0.github.io/hadiths/data.html?edition=eng-abudawud&type=section&num=4#hadith:eng-abudawud:1198:~:text=Reference%3A%20Book%204%20Hadith%201) refers to [section 4](https://fawazahmed0.github.io/hadiths/data.html?edition=eng-abudawud&type=section&num=4#:~:text=Search-,Section%204,-%3A%20Prayer%20(Kitab%20Al) and so on.

Sorry brother, i didn't got it .
//////////////////////////
{
  "metadata": {
    "name": "Sahih al Bukhari",
    "section": {
      "97": "Oneness, Uniqueness of Allah (Tawheed)"
    }
  },
  "hadiths": [
    {
      "hadithnumber": 7562,
      "arabicnumber": 7562,
      "text": "Narrated Abu Sa`id Al-Khudri:The Prophet (ﷺ) said, \"There will emerge from the East some people who will recite the Qur'an but it will not exceed their throats and who will go out of (renounce) the religion (Islam) as an arrow passes through the game, and they will never come back to it unless the arrow, comes back to the middle of the bow (by itself) (i.e., impossible). The people asked, \"What will their signs be?\" He said, \"Their sign will be the habit of shaving (of their beards and their heads). (Fath-ul-Bari, Page 322, Vol. 17th)",
      "grades": [],
      "reference": {
        "book": 97,
        "hadith": 187
      }
    }
  ]
}
////////////////////////////
please explain it in this context.

**Comment by kaisersakhi** [comment]
> > Assalaamualikum brother,
> > I need all the books in a database, i'm converting all this json into a RDBMS but i have a little confusion..
> > ///////////////////
> > ```
> >   "reference": {
> > 
> >     "book": 4,
> > 
> >     "hadith": 1
> > 
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ////////////////
> > Can you explain this bit, how does this work, i mean what is this book number and hadith number does it refers to the book of the same number and like wise hadith if so then book number shouldn't exceed 6, or in this case 7, but it does.
> > Please correct me!
> > Thank you!
> 
> Wa aleykum assalam wa rahmatullahi wa barakatuh, It would be great if you upload your RDBMS or the script after you've finished, so we can all benefit from that.

Inshallah brother, I will do that once done

**Comment by fawazahmed0** [comment]
>  what is this book number and hadith number does it refers to the book of the same number and like wise hadith if so then book number shouldn't exceed 6, or in this case 7, but it does.

book number refers to section number and book number is always same as section number

For example, if book number is 97, then it refers to section number 97 : Oneness, Uniqueness of Allah (Tawheed).


**Extra Information:**

The reason I used "book" instead of "section" is because, in arabic version they refer the "section" as "book"
For example, the section number 97 Oneness, Uniqueness of Allah (Tawheed) is called as كتاب التوحيد or kitab al tawheed (book of taweed ) in arabic.
And when scholars give reference to a hadith, they will sometimes give reference as book 97, hadith 187 (and not section 97, hadith 187). That's the only reason for using "book" instead of "section".

**Comment by kaisersakhi** [comment]
Thank you so much brother, I've been idiot all this time !
