### ISSUE TITLE
apiscript needs to be fixed for ahadith which contain multiple narration

### ISSUE THREAD

**Issue by unkn4wn** [fawazahmed0/hadith-api#29]
Asselamu Aleykum,
**Two Issues**

**Issue 1:** 
Example:
1.
[Turkish Tirmidhi 3604](https://cdn.jsdelivr.net/gh/fawazahmed0/hadith-api@1/editions/tur-tirmidhi/3604.json)
You can only see "3604"
3604.1, 3604.2 etc are missing completely instead of mentioning them with an empty text like here:
[English Muslim 2](https://cdn.jsdelivr.net/gh/fawazahmed0/hadith-api@1/editions/eng-muslim/2.json)
2.
You can only see "3604, 3604.2, 3604.3 3604.4, 3604.5, 3604.6, 3604.7, 3604.8, 3604.9, 3604.10" if text isn't empty like here.
[English Tirmidhi 3604](https://cdn.jsdelivr.net/gh/fawazahmed0/hadith-api@1/editions/eng-tirmidhi/3604.json)

This is only one example from many ones. All ahadith which don't have any translation should be shown with an empty text. For "Integers" this works perfectly fine but as soon as you try it with an "Double" Hadithnumber like 3604.2, 3604.3 etc it is missing completely instead of an empty text.

Especially for me this is important because I am iterating through the Arabic and Translated json file. So if the 3605th position of the arabic file is "Hadith 1604.2" while the 3605th position of the Turkish file is "Hadith 3605", this would lead to wrong results.

**Issue 2:**
All "Double" Hadithnumbers like "3604.1, 3604.2" etc are always shown as "book 0, chapter 0" :
[English Tirmidhi 3604](https://cdn.jsdelivr.net/gh/fawazahmed0/hadith-api@1/editions/eng-tirmidhi/3604.json)
instead of 
```
"book": 48,
"hadith": 236
``` 
and so on....

**Comment by fawazahmed0** [comment]
> Especially for me this is important because I am iterating through the Arabic and Translated json file. 

You should match arabic `hadithnumber` with translated json `hadithnumber`.

You can also use:
https://cdn.jsdelivr.net/gh/fawazahmed0/hadith-api@1/editions/ara-tirmidhi/{hadithnumber}.json
https://cdn.jsdelivr.net/gh/fawazahmed0/hadith-api@1/editions/tur-tirmidhi/{hadithnumber}.json
to get the same hadith


Inshallah will look into these issues later and try to fix them all.

**Comment by unkn4wn** [comment]
I'm using it offline and I know what you mean but the problem is if the text is empty just like with the "Integer" Hadithnumbers you just need to check "Is 3605th position text empty?" in translated json file to know the existence. This can be established relatively fast.

But if its missing completely just like with the "Double" Hadithnumbers instead of showing just an empty text, you're forced to iterate through the translated json file after every hadith in Arabic json file to check if the hadithnumbers/arabicnumbers are identical with the translated one.

InshaaAllah
