### ISSUE TITLE
Found a few trunctated hadith.

### ISSUE THREAD

**Issue by GibreelAbdullah** [fawazahmed0/hadith-api#34]
https://raw.githubusercontent.com/fawazahmed0/hadith-api/1/editions/eng-nasai/4255.json

It was narrated that Khalid said:"Al-Miqdam bi

https://sunnah.com/nasai:4255

It was narrated that Khalid said:
"Al-Miqdam bi8n Ma di Karib came to visit Mu awiyah and said to him: I adjure you by Allah, do you know that the messenger of Allah forbade wearing the Hides of predators and riding on them? He said: 'yes."

**Comment by GibreelAbdullah** [comment]
https://raw.githubusercontent.com/fawazahmed0/hadith-api/1/editions/eng-nasai/2781.json

"It was narrated from Hafsah, the wif"

https://sunnah.com/nasai:2781

"It was narrated from Hafsah, the wif3e of the Prophet, that she said:
"O Messenger of Allah, why is it that the people have exited Ihram for Umrah but you have not exited your Ihram for Umrah? He said: "I have matted my hair and garlanded my Hadi, so I will not exit Ihram until I have offered the sacrifice."

**Comment by GibreelAbdullah** [comment]
I can correct them, can you tell me how exactly do I do that?

You mentioned something related to github actions. I am not aware about that.

**Comment by fawazahmed0** [comment]
Ok, if you want to correct mistakes or add something missing, this is how it should be done:

For Text Correction:
Go [here](https://github.dev/fawazahmed0/hadith-api/tree/1/database/linebyline) and directly edit the text and create a PR.

For Grades correction:
Go [here](https://github.dev/fawazahmed0/hadith-api/tree/1/database/linebyline/info.json) and directly edit the grades in info.json and create a PR.

If you want to edit something else, please do ask me.

I will take care of Github actions thing.

p.s I will review your PR and merge the changes and then run the github actions
