### ISSUE TITLE
Section 0

### ISSUE THREAD

**Issue by Shaeikh** [fawazahmed0/hadith-api#40]
Why there is section 0? It is confusing me with my code, some books dosent got it but some got 
what is it?

**Comment by fawazahmed0** [comment]
Hadiths which did not belong into any other section were placed into section 0.
one book do actually have section 0, it's sahih muslim. Other books don't have section 0 as far as i know.

**Comment by Shaeikh** [comment]
> Hadiths which did not belong into any other section were placed into section 0. one book do actually have section 0, it's sahih muslim. Other books don't have section 0 as far as i know.

no my code says there are 5 hadiths book with 0 section

Sahih al Bukhari
Sunan Ibn Majah
Sahih Muslim
Sunan an Nasai
Jami At Tirmidhi

ill check again if i am mistaken

Jazak Allah

**Comment by Shaeikh** [comment]
> > Hadiths which did not belong into any other section were placed into section 0. one book do actually have section 0, it's sahih muslim. Other books don't have section 0 as far as i know.
> 
> no my code says there are 5 hadiths book with 0 section
> 
> Sahih al Bukhari Sunan Ibn Majah Sahih Muslim Sunan an Nasai Jami At Tirmidhi
> 
> ill check again if i am mistaken
> 
> Jazak Allah

Yea i checked and there are 5 books with section 0

**Comment by fawazahmed0** [comment]
Yes there are 5 books with section 0 in my API, I actually meant something else (i.e [sahih muslim has Introduction section](https://sunnah.com/muslim) which is equivalent to section 0, other books don't have this section) 

**Update:**
Ibn majah also has section 0, inaddition to sahih muslim
