### ISSUE TITLE
Parsing issue in infofixer

### ISSUE THREAD

**Issue by unkn4wn** [fawazahmed0/hadith-api#48]
Asselamu Aleykum,

I am trying to add [3604j ](https://sunnah.com/tirmidhi:3604j)(3604.10) to the info.json file. However, I am unable to add 3604.10 as it gets automatically replaced with 3604.1 after running the infofixer. This is most likely due to the fact that in the context of math, 3604.1 and 3604.10 are equivalent.

Is there any way to resolve this issue without converting the float to a string?

![image](https://user-images.githubusercontent.com/103898825/219978285-5f1c6284-eec3-452f-a7c6-95b30947165c.png)

**Comment by fawazahmed0** [comment]
replace 3604.1 -> 3604.01, 3604.2 -> 3604.02,  .................   3604.10 -> 3604.1
