### ISSUE TITLE
Remove Section 0 in "sections" and "section_details"

### ISSUE THREAD

**Issue by unkn4wn** [fawazahmed0/hadith-api#55]
Asselamu Aleykum,
Maybe removing Section 0 except in "[Sahih Muslim](https://raw.githubusercontent.com/fawazahmed0/hadith-api/1/editions/eng-muslim.json)" and "[Sunan ibn Majah](https://raw.githubusercontent.com/fawazahmed0/hadith-api/1/editions/eng-ibnmajah.json)" is a good idea because there is no need for that.

For example in "[Jami at Tirmidhi](https://raw.githubusercontent.com/fawazahmed0/hadith-api/1/editions/eng-tirmidhi.json)" its even more confusing because "sections" starts with 0 while "section_details" starts with 1

**Comment by fawazahmed0** [comment]
Jazakallah,  I have updated the values for section_details 0, should be fixed now.
let me know if there is any other issue
