### ISSUE TITLE
read files

### ISSUE THREAD

**Issue by kasimi17** [fawazahmed0/hadith-api#58]
I can't read files
 thanks to help me

**Comment by GibreelAbdullah** [comment]
What do you mean? Please elaborate.

**Comment by kasimi17** [comment]
I read it using linux os

**Comment by GibreelAbdullah** [comment]
I use Linux as well.

Which file? How are you trying to read?

Did you download the file and open it with a text editor. Or are you hitting the API to get the data and view it in browser?

**Comment by kasimi17** [comment]
using Linux to download the files then open it with a text editor in windows

**Comment by GibreelAbdullah** [comment]
`using Linux to download the files then open it with a text editor in windows`

I don't understand. Kindly respond with as much detail as possible. Otherwise you are wasting both of our time. Include screenshots, error logs etc.

**Comment by fawazahmed0** [comment]
> using Linux to download the files then open it with a text editor in windows

You can download files by clicking [here](https://github.com/fawazahmed0/hadith-api/archive/refs/heads/1.zip) , the files will be in database/linebyline folder
