### ISSUE TITLE
Translation error in Zubair Ali Zai grading.

### ISSUE THREAD

**Issue by GibreelAbdullah** [fawazahmed0/hadith-api#59]
https://github.com/fawazahmed0/hadith-api/blob/1/editions/eng-tirmidhi/3377.json
it says 

Son Mountain Pleased Allah With him Of the Say Of Sanaad Disconnected Sheikh Mercy Allah By Told Extra Son My father Extra Son did not Son Mountain Pleased Allah With him And See Research Articles (4/ 566)

https://zubairalizai.com/tirmizi/3377/

معاذ بن جبل رضی اللہ عنہ کے قول کی سند منقطع ہے، شیخ رحمہ اللہ نے فرمایا: ’’زیاد بن أبي زیاد مولی ابن عیاش لم یدرک معاذ بن جبل رضي اللّٰہ عنہ‘‘، وانظر تحقیقی مقالات (4/ 566)

2 options - either to remove the grading in this hadith or to put a better translation which I am writing below.

The chain of Muadh ibn Jabal (رضی اللہ عنہ)'s narration is disconnected. Sheikh (Zubair) رحمہ اللہ said, "Ziyad bin Abi Ziyad, the freed slave of Ibn Ayyash did not meet  Muadh ibn Jabal (رضی اللہ عنہ)". See Research Articles (4/ 566)

I personally think it should be removed since it is too big.

**Comment by GibreelAbdullah** [comment]
https://zubairalizai.com/abudawood/611/ has similar longer text, but I think it is manageable since it is not too long

https://zubairalizai.com/abudawood/465/ needs translation correction as well.
It is currently
"Isnaad Sahih Sahih Muslim (713 And why Mentioned Give Salam Ali Prophet)"
It should be
"Isnaad Sahih Sahih Muslim (713 but did not mention giving Salam to the Prophet ﷺ)"

**Comment by GibreelAbdullah** [comment]
Let me know what needs to be done in these cases. I can raise a PR with manual correction.

**Comment by fawazahmed0** [comment]
Jazakallah, [should be fixed now](https://github.com/fawazahmed0/hadith-api/commit/a77dbe779dd608e9bceb974c88f567c1b5d085ac)

**Comment by GibreelAbdullah** [comment]
@fawazahmed0 brother.

https://zubairalizai.com/nasai/352/ says it is "Sahih"

https://github.com/fawazahmed0/hadith-api/blob/1/editions/ara-nasai/352.json calls it "Sahih Muslim."
