### ISSUE TITLE
Translation and grading discrepancy in Sunan Nasai.

### ISSUE THREAD

**Issue by GibreelAbdullah** [fawazahmed0/hadith-api#60]
https://sunnah.com/nasai:352 and https://sunnah.com/nasai:353 are same.

but hadith-api has different grading for both.

https://github.com/fawazahmed0/hadith-api/blob/1/editions/ara-nasai/352.json (Al-Albani : Sahih) 

https://github.com/fawazahmed0/hadith-api/blob/1/editions/ara-nasai/353.json (Al-Albani : Daif)

**Comment by GibreelAbdullah** [comment]
Same for 4938 and 4939

https://github.com/fawazahmed0/hadith-api/blob/1/editions/ara-nasai/4938.json

https://github.com/fawazahmed0/hadith-api/blob/1/editions/ara-nasai/4939.json

**Comment by fawazahmed0** [comment]
Jazakallah, I corrected [the grades](https://github.com/fawazahmed0/hadith-api/commit/6d99c122fb3f50a9685c6acfc5c7aee6c5235126) by referring al-maktaba grades
