### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by fawazahmed0** [fawazahmed0/hadith-api#67]
https://hadis.uk/sborniki-xadisov/saxix-al-buxari/
https://asar-forum.com/viewforum.php?f=87
https://sunna.e-minbar.com/sunan-abu-davud/kniga-18/glava-01/
https://isnad.link/book/sahih-muslim

**Comment by ahmedazhar05** [comment]
السلام عليكم @fawazahmed0 
Can I take up this issue?
I have already started working on scraping russian hadith data from the links you provided

**Comment by fawazahmed0** [comment]
walaikum salam, yes you can take this issue, but remember, you need scrape both arabic and russian text together

**Comment by ahmedazhar05** [comment]
> walaikum salam, yes you can take this issue, but remember, you need scrape both arabic and russian text together

noted!

**Comment by ahmedazhar05** [comment]
One question that I have.
Can we have '\n' in the hadith text to separate multiple paragraphs that are within a single hadith, or do we merge them with a space?

**Comment by fawazahmed0** [comment]
'\n' would be better

**Comment by ahmedazhar05** [comment]
Russian translation of **Sahih Al Bukhari** has been added, more to be added soon
إن شاء الله

**Comment by fawazahmed0** [comment]
Added muslim & abudawud.
Not adding tirmidhi, nasai and ibnmajah as the number of hadiths are few in numbers

**Comment by ahmedazhar05** [comment]
I see that the Russian text of some of the hadiths in Bukhari have been completely removed in c5fced, who so?
