### ISSUE TITLE
Hadith empty

### ISSUE THREAD

**Issue by md-rifatkhan** [fawazahmed0/hadith-api#73]
https://cdn.jsdelivr.net/gh/fawazahmed0/hadith-api@1/editions/ben-muslim/sections/0.json

**Comment by fawazahmed0** [comment]
there are few missing hadiths for each language, for example [english](https://cdn.jsdelivr.net/gh/fawazahmed0/hadith-api@1/editions/eng-muslim/sections/0.json), [arabic](https://cdn.jsdelivr.net/gh/fawazahmed0/hadith-api@1/editions/ara-muslim/sections/0.json)
