### ISSUE TITLE
Possible documentation website for various APIs. 

### ISSUE THREAD

**Issue by yahia-berashish** [fawazahmed0/hadith-api#78]
Alsalam ealaykum @fawazahmed0 
I've noticed your Quran and Hadith APIs among others, which I think are very useful, I'm a web developer who has been developing reactive web apps and websites for several years now, primarily using React, Next, Vite, and Astro. 
I'm writing this issue to know if you're interested in a centralized documentation website for the various APIs you've developed, I'm ready to build it completely free of charge and deploy it in any platform you prefer (Vercel, Netlify, etc...), I just think your work is really helpful, and I would like to help it grow. 
Thanks for your time, hope to connect soon.

**Comment by fawazahmed0** [comment]
walaikum assalam @yahia-berashish,
> if you're interested in a centralized documentation website for the various APIs you've developed

Thank you for the help, currently this is not needed. GitHub readme file seems to be enough.
