### ISSUE TITLE
Question about the quality

### ISSUE THREAD

**Issue by AliOsm** [fawazahmed0/hadith-api#8]
First of all thanks for this work!

I want to build on top of your data, so can I trust the data quality?
It will be helpful if you can mention the data sources.

Best,
Ali Fadel

**Comment by fawazahmed0** [comment]
Yes brother, you can use the data.
Here is the [sources](https://github.com/fawazahmed0/hadith-api/blob/1/References.md)

For english and arabic data, I got from sunnah.com , and for other translations I used multiple websites as data source,
And grades(sahih, daif etc) , I got from [al-maktaba.org](https://al-maktaba.org/)

Just refer the [sources](https://github.com/fawazahmed0/hadith-api/blob/1/References.md).

**Comment by AliOsm** [comment]
Thanks for your response, and thanks for your hard work!
