### ISSUE TITLE
403 Server response

### ISSUE THREAD

**Issue by SaidSolsaev** [fawazahmed0/hadith-api#95]
Assalamu Aleykum brother. I am building a project with your api and i am getting a server error with status code 403 when using the api, sometimes it works other times i just get error when fetching a hadith, i have tried multiple languages.

**Comment by fawazahmed0** [comment]
could you please provide me the link which is showing 403 error and screenshot of error page

**Comment by fawazahmed0** [comment]
Ok, thanks. I too am getting 403's. Please wait while it gets fixed.

Also please see [this](https://github.com/fawazahmed0/hadith-api?tab=readme-ov-file#:~:text=Warning%3A%20You%20should%20include%20fallback%20mechanism%20in%20your%20code%2C%20to%20avoid%20issues)

**Comment by SaidSolsaev** [comment]
Thank you.

11. des. 2024 kl. 20:58 skrev Fawaz Ahmed ***@***.***>:

﻿

Ok, thanks. I too am getting 403's. Please wait while it gets fixed.

Also please see this<https://github.com/fawazahmed0/hadith-api?tab=readme-ov-file#:~:text=Warning%3A%20You%20should%20include%20fallback%20mechanism%20in%20your%20code%2C%20to%20avoid%20issues>.

**Comment by fawazahmed0** [comment]
should be fixed now
